### ISSUE TITLE
Issues with < and >

### ISSUE THREAD

**Issue by ivankokan** [TeX-Live/yhmath#1]
Hi @norbusan, I have tested the version 1.4 a bit, and found two issues on `<` and `>`, please check the following MWE.

```
\documentclass{article}

\usepackage{amsmath}
\usepackage{amssymb}

\usepackage{yhmath}


\listfiles

\begin{document}

\[
  \sqrt{n +
    \sqrt{(n - 1) +
      \sqrt{(n - 2) + \dotsb +
        \sqrt{2 +
          \sqrt{1}
        }
      }
    }
  }
  <
  \sqrt{n}_{n > 0} + 1.
\]

\[
  \left(1 + 2 + \frac{3}{\sqrt{x}}\right)
  \left(\frac{\sqrt{y} - 4}{\sqrt{z} - 0} + 43 - \frac{\sqrt{y} - 3}{\sqrt{z} + 8}\right)
  = 123 - 4\sqrt{5}.
\]

\[
  \wideparen{AB}
\]

\end{document}
```

![image](https://user-images.githubusercontent.com/1058211/53243221-7dd41480-36a7-11e9-8070-462f10026eda.png)

**Comment by RuixiZhang42** [comment]
@ivankokan Please confirm that the only issue here is about `<` and `>` (your MWE contains many other math symbols). I also found problem with `/`.

@norbusan This should be an easy fix. Three lines *must be added* to the newly introduced `\DeclareMathDelimiter...` in `yhmath.dtx`:

```tex
\DeclareMathDelimiter{<}{\mathopen}{symbols}{"68}{yhlargesymbols}{"0A}
\DeclareMathDelimiter{>}{\mathclose}{symbols}{"69}{yhlargesymbols}{"0B}
\DeclareMathSymbol{<}{\mathrel}{letters}{"3C}% must be added
\DeclareMathSymbol{>}{\mathrel}{letters}{"3E}% must be added
\DeclareMathDelimiter{/}{\mathord}{operators}{"2F}{largesymbols}{"0E}
\DeclareMathSymbol{/}{\mathord}{letters}{"3D}% must be added
```

Since `\DeclareMathDelimiter` makes `<` and `>` delimiters regardless of the context whilst they should normally be considered as relations — and they come from completely different font. Similar consideration applies to `/` as well. Please refer to https://github.com/latex3/latex2e/blob/master/base/fontdef.dtx *Subsubsection: Delimitercodes for characters* for documented explanations.

**Comment by norbusan** [comment]
v1.5 released with the respective changes, thanks everyone!

**Comment by ivankokan** [comment]
> @ivankokan Please confirm that the only issue here is about `<` and `>` (your MWE contains many other math symbols). I also found problem with `/`.

Hi @RuixiZhang42. Yes, `<` and `>` were my only concern. I see that the issue is fixed now and the analog issue for `/` is resolved as well. Is there any other to handle in similar fashion?

**Comment by ivankokan** [comment]
> Hi @RuixiZhang42. Yes, `<` and `>` were my only concern. I see that the issue is fixed now and the analog issue for `/` is resolved as well. Is there any other to handle in similar fashion?
